# Generated by Django 5.2.4 on 2025-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_property_description_en_property_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('арендодатель', 'арендодатель'), ('гость', 'гость')], default='гость'),
        ),
    ]
